### ISSUE TITLE
ALIGNER:chainMerge (chainmerge) FAILED  

### ISSUE THREAD

**Issue by shwetaramdas** [evotools/nf-LO#11]
Dear nd-LO developers,

I'm trying to align two local genome assemblies using nfLO, and get the following error at the bottom of the 'reports/execution_trace.txt'
file. Could you please help me figure out why?

``````````
701855  fc/df1139       144312  ALIGNER:axtChain (axtchain_m)   COMPLETED       0       2023-02-06 05:52:10.789 926ms   733ms   101.9%  133.3 MB        415.4 MB      90 MB   3.6 KB
701856  ca/843384       160553  ALIGNER:chainMerge (chainmerge) FAILED  139     2023-02-06 06:22:34.216 21.1s   21s     -       -       -       -       -
701857  dd/25d4a1       160837  ALIGNER:chainMerge (chainmerge) FAILED  139     2023-02-06 06:23:02.349 21.1s   21.1s   -       -       -       -       -
701858  76/995157       161063  ALIGNER:chainMerge (chainmerge) FAILED  139     2023-02-06 06:23:30.339 21.5s   21.5s   -       -       -       -       -
```````

The code I used was:

 nextflow run evotools/nf-LO --source ../GCA_021130815.1_PanTigT.MC.v3_genomic.fna.gz --target ~/data/hg38.fa.masked.gz --outdir ../NFLOW


When the code failed, it had created three directories: genome2bit, singlechains, and reports. 

Please let me know if you need more information from me,
Shweta

**Comment by RenzoTale88** [comment]
Hi @shwetaramdas 
thanks for using nf-LO. 
Could you try running the workflow with decompressed fasta files? I believe that might be the source of the issue.
Thanks 
Andrea

**Comment by shwetaramdas** [comment]
Dear Andrea,

I'm trying this now and it has been running for a while--I will update you about whether it works. Thank you!

**Comment by RenzoTale88** [comment]
@shwetaramdas of course, you can try figure out the issue by looking into the folder starting with `./work/fb/7305fc` (e.g. by using `ls -al ./work/fb/7305fc*/`). This folder should contain many files, including one called `.command.err`, that should contain some more info about why the work failed (`cat ./work/fb/7305fc*/.command.err`).
One more suggestion is to tweak the configuration for your genome. I can see that you have processed over 350K fragments, which is way too mamy. Try to increase the fragment size (`--tgtSize` and `--srcSize`) and the chunk overlap (`--tgtSize` and `--srcSize`). You can find some examples with large genomes in the supplementary table 1 of the nf-LO manuscript. I'll update the documentation to discuss about avoiding over fragmentation since I realise it is not well documented.

**Comment by shwetaramdas** [comment]
Thank you, @RenzoTale88 . I will try that. As an alternative, I used default parameters. and split the source files by chromosome (and kept the target fasta file intact). Those ran without error. Would these chains (one per source chromosome) be reasonable to use as well?

Thank you,
Shweta

**Comment by RenzoTale88** [comment]
I would recommend to try editing the parameter, in order  to consider all possible combination of chromosomes. The default parameters are ok for small genomes, but for larger ones I would definitely recommend larger fragments. Also, the fact that you can run it chromosome by chromosome means that it is likely an issue of overfragmentation.

Andrea
________________________________

**Comment by RenzoTale88** [comment]
Closing
